### ISSUE TITLE
Some folder structure changes in the future

### ISSUE THREAD

**Issue by jmaicaaan** [UltraRangers/gauntlet#13]
Awhile ago, me and @cedrickmandocdoc talked about some new folder structures most especially in the server side. Currently, we have the server folder then inside it contains `www` folder which mainly focus on starting the server, not the starting/creating the **whole application**. They are different. The other folder is the `app` which contains another sub-folder `modules`.

We defined the `modules` based from the entities or what we call `folder-by-feature`. So for example, if we have a User entity we would have a `user` folder inside it. If we have another entity like Location entity we would have a `location` folder inside it. Basically it is a modular type based from the entities of the application.

The changes that **might** come would be the following:

Inside the `src` folder we would (**this is also for the client structure**) we would have the `app` as the root of application. Then inside the `app` folder contains `core`, `shared` and other "feature modules" as the [Angular docs say](https://angular.io/guide/styleguide#feature-modules).

By the way, I'm trying to apply the the `LIFT` principle by the Angular team. Here's the [link](https://angular.io/guide/styleguide#folders-by-feature-structure) for reference. Setting one structure for both client and server since `nest.js` is inspired by the `Angular`. I think it would be better to follow some guidelines from them.

Here are my 3 proposals structure:

![server1](https://user-images.githubusercontent.com/13105222/37711644-5245218e-2d4c-11e8-88f3-f06e0f5225bc.png)
![server2](https://user-images.githubusercontent.com/13105222/37711646-537d96ee-2d4c-11e8-90dd-39245e6e5a9f.png)
![server3](https://user-images.githubusercontent.com/13105222/37711651-5534888a-2d4c-11e8-9465-1059098c4ca5.png)

**Comment by cedrickmandocdoc** [comment]
@john20xdoe @dach020

**Comment by jmaicaaan** [comment]
I believe we need to finilized this another structure before continuing for #11
