### ISSUE TITLE
Next milestone discussion 🔥

### ISSUE THREAD

**Issue by jmaicaaan** [UltraRangers/gauntlet#28]
What I have on mind right now are these things:

- Full featured CMS support (probably let's give the demo site a little bit interaction)
- Add a place in the client side to display the current version deployed (from the prev. conversation with @john20xdoe)
- Email support (do we need to have this already?)
- Make the `migrations` use `Table` instead of raw query for better readability (?)

Also, another feature into the list component in the client, that will automatically request to the specified endpoint? 🤔 

cc: @john20xdoe @cedrickmandocdoc

**Comment by jmaicaaan** [comment]
If you agree with the email support, we'll prolly add the reset password support also 🙆‍♂️

**Comment by john20xdoe** [comment]
For the CMS support, we could maybe create the client-side from our vue.js template from @jm-4life . Though I',m not sure if we should create a new repo for it or just include it with gauntlet?

**Comment by john20xdoe** [comment]
Oh wait, nevermind about the vue. We already have angular here, right?

**Comment by jmaicaaan** [comment]
I'm not sure if we would like to have the subscribed notification part already. But the Account related features is a must 👍 

What is the difference between the SendMail you are mentioning and also this [SendGrid](https://elements.heroku.com/addons/sendgrid)?

For the CMS, we already have set up the angular here. The vue-template, we could work on it to another repository soon. You could see in our demo site a preview  🥂

**Comment by john20xdoe** [comment]
Yes, subscriptions are nice-to-have but not required.

Oops, I stand corrected, I do mean SendGrid hahaha. Been awhile since I've used it...

**Comment by john20xdoe** [comment]
The configuration for email credentials will also be managed similar to the database.. perhaps again via environment variables.

BTW using SendGrid is not required. For basic sending, we can also test just by using Gmail's POP or IMAP credentials. https://support.google.com/mail/answer/7104828?hl=en  PRobably using aliases like ultrarangers**+testnotifs**@gmail.com

**Comment by jmaicaaan** [comment]
Is there any difference in using SendGrid rather than Gmail?

**Comment by john20xdoe** [comment]
SendGrid is much more reliable, and better designed to send mass emails. For GMail, we can use it for dev purposes since it is already set up. However, it doesn't look official, plus free GMail has limits for sending mass emails to prevent abuse and spam (unless setup with GSuite), which will sometimes result in random failures when sending. Also, using the Gmail IMAP and POP outside of email clients will raise an alert in your account for "Less secure apps" https://support.google.com/accounts/answer/6010255?hl=en

**Comment by jmaicaaan** [comment]
Thanks for the info 👍 

Let's just wait for @cedrickmandocdoc if he has any thing to suggest in our next milestone beside from the email features!

**Comment by cedrickmandocdoc** [comment]
Yes email support is good.
For migrations using Table is good also.
For the table that automatically request, it is also good.
Let's do this all.

**Comment by cedrickmandocdoc** [comment]
How about we add this on our list:
- Continuous Deployment for different environments (testing, staging, production)
- Provide OAuth in the server

**Comment by john20xdoe** [comment]
For CD, we can setup Heroku pipelines (test, staging) in the current Heroku app, or maybe the workflows in CircleCI (I don't know how to set up CircleCi for now). Although, I think staging and production is not that important unless we are actually creating a full non-demo app made from gauntlet (the purpose of staging and prod are for other users). 

For test env though, it is necessary to run tests, but not unit tests (that is what CircleCI is for). The test env is for integration and UI tests, again of an app implementing **gauntlet**.

**Comment by jmaicaaan** [comment]
I think other environments such as staging and prod is not necessary for us to work on. But the test environment is a must.

Summarizing the discussion here is the list of items I have for our next milestone

- CMS Demo (login, dashboard, profile & reset password pages)
- Email support (we can the email provider from the slack last time if you guys remembered. Please add it here)
- A place in the UI where we see the deployed version

Some things are not necessary yet. What are yout thoughts? If everything's good, I'll create the issues/tickets for it 🔥

**Comment by cedrickmandocdoc** [comment]
Everything is good to me haha, Lets get this done. And also remember the issue in the provider it causes circular import I guess in the case of entities, repositories etc having exported in index. But I don't know the real issue.
I do have a suggestion, putting the entities in common? yeah I just realized right now what you said to me last time about that, that it should be in common is right.

**Comment by jmaicaaan** [comment]
What have you realized in the entities part? Hmm, that would change again a few things in our structure.

**Comment by jmaicaaan** [comment]
Anyways, I've added the new tickets both client and server. Here is the new [milestone](https://github.com/UltraRangers/gauntlet/milestone/2) 🔥
