### ISSUE TITLE
Fix CI logs error

### ISSUE THREAD

**Issue by jmaicaaan** [UltraRangers/gauntlet#7]
See the previous builds to get a "view" or "pattern" on why the CI is failing...

https://circleci.com/gh/UltraRangers/gauntlet/tree/develop

I guess we need to specify the node version engine into the `package.json` and also add some dependencies we missed

**Comment by cedrickmandocdoc** [comment]
This is fix in develop and master, I think we can close this now

**Comment by jmaicaaan** [comment]
Yeah let me close it. Fixed by [PR](https://github.com/UltraRangers/gauntlet/pull/9)
